Revert "enforce dump permission on dump()"
Stability blocker.

java.lang.SecurityException: Requires DUMP: Neither user 1001 nor current process has android.permission.DUMP.
       at android.app.ContextImpl.enforce(ContextImpl.java:1893)
       at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1922)
       at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:593)
       at com.android.phone.TelephonyDebugService.dump(TelephonyDebugService.java:50)
       at android.app.ActivityThread.handleDumpService(ActivityThread.java:2813)
       at android.app.ActivityThread.access$2300(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
This reverts commit 8e4dae587f8a4dd20b06c16e4f7fd3723ff56774.

Bug: 18090004
Change-Id: Id9a549971dbe7a5b4baeb7067967cd791541cf4a